/**
 * Onyx Base — Request ID infrastructure.
 *
 * Every API request gets a unique, traceable `req_` ID. The ID is:
 *   1. Generated by the API handler wrapper (or middleware).
 *   2. Echoed back in the `X-Request-Id` response header.
 *   3. Embedded in the JSON body of EVERY response (success or failure).
 *   4. Logged alongside the operation, so a single ID can be grepped from
 *      server logs to find the exact failure point.
 *
 * This is the cornerstone of "never hide an error" — when a user sees an
 * error toast in the UI, the toast includes the request ID, and the operator
 * can search the server logs for that exact ID to find the root cause.
 */

import crypto from 'crypto'

/**
 * Generate a fresh, URL-safe, globally-unique request ID.
 *
 * Format: `req_` + 22 base64url chars (from 16 bytes of crypto-grade randomness).
 * The total length is 26 chars — short enough to fit in a log line, long
 * enough to make collisions effectively impossible.
 *
 * Note: Node's `crypto.randomBytes().toString()` does NOT support `base32url`
 * (only `base64`, `base64url`, `hex`, `latin1`). We use `base64url` here.
 */
export function newRequestId(): string {
  // 16 bytes → 22 base64url chars (no padding). We slice to 22 for safety.
  return 'req_' + crypto.randomBytes(16).toString('base64url').replace(/=/g, '').slice(0, 22).toLowerCase()
}

/**
 * Extract a request ID from an incoming request, or mint a new one.
 *
 * Resolution order:
 *   1. `X-Request-Id` header (if the caller — e.g. the CLI or a webhook —
 *      supplied one). We TRUST the caller's ID as long as it matches our
 *      format. This allows distributed tracing across the CLI → API boundary.
 *   2. A fresh ID via `newRequestId()`.
 *
 * We NEVER accept arbitrary caller-supplied IDs that don't match our format
 * (an attacker could otherwise inject misleading trace IDs into logs).
 */
export function resolveRequestId(headers: Headers): string {
  const incoming = headers.get('x-request-id') || headers.get('x-correlation-id')
  if (incoming && /^req_[a-z0-9]{16,32}$/i.test(incoming)) {
    return incoming.toLowerCase()
  }
  return newRequestId()
}

/**
 * Build a ResponseInit that includes the `X-Request-Id` header so the client
 * can read it back even on errors. Use this as the `init` arg to `Response.json()`
 * or pass it directly to a Next.js `Response`.
 *
 * Example:
 *   return Response.json({ ok: false, error: '...', requestId }, withRequestId(requestId, { status: 400 }))
 */
export function withRequestId(requestId: string, init: ResponseInit = {}): ResponseInit {
  return {
    ...init,
    headers: {
      ...(init.headers ?? {}),
      'X-Request-Id': requestId,
    },
  }
}

/**
 * Structured logger that includes the request ID + operation tag.
 * Use this instead of bare `console.log/error` inside API handlers so every
 * log line is greppable by request ID.
 *
 * CRITICAL: this logger REDACTS known-secret fields. Never log:
 *   - bot tokens (regex: `\d+:[A-Za-z0-9_-]{30,}`)
 *   - API keys (`kv_live_*`, `onyxbase_*`, `st_*`)
 *   - Authorization headers
 *   - password fields
 *
 * Anything that looks like a secret is replaced with `[REDACTED]`.
 */
export function logRequest(
  requestId: string,
  operation: string,
  fields: Record<string, unknown>,
  level: 'info' | 'warn' | 'error' = 'info',
): void {
  const safeFields = redact(fields)
  const line = JSON.stringify({
    ts: new Date().toISOString(),
    requestId,
    operation,
    level,
    ...safeFields,
  })
  if (level === 'error') console.error(line)
  else if (level === 'warn') console.warn(line)
  else console.log(line)
}

const SECRET_PATTERNS: Array<{ re: RegExp; replacement: string }> = [
  // Telegram bot tokens: "123456789:AA..."
  { re: /\b\d{8,}:[A-Za-z0-9_-]{20,}\b/g, replacement: '[REDACTED_BOT_TOKEN]' },
  // Onyx Base API keys
  { re: /\b(?:kv_live_[A-Za-z0-9]{16,}|onyxbase_[A-Za-z0-9]{8,}|st_[A-Za-z0-9]{16,})\b/g, replacement: '[REDACTED_API_KEY]' },
  // MCPEmail user keys (mcpe_<64-hex> or any mcpe_ payload ≥20 chars)
  { re: /\bmcpe_[A-Za-z0-9_-]{20,}\b/g, replacement: '[REDACTED_MCPE_KEY]' },
  // Bearer headers
  { re: /Bearer\s+[A-Za-z0-9._-]+/gi, replacement: 'Bearer [REDACTED]' },
  // key=value style secret leaks in dumps / query strings
  { re: /\b(?:api_key|mcpemail_key|mcpe_key|token|secret|password)=([^\s&"']+)/gi, replacement: '$1=[REDACTED]' },
]

/** Public: scrub known secret shapes out of an arbitrary string (error
 *  messages, upstream response fragments) before they reach a response or
 *  a log line. Defense in depth for the zero-credential-leakage rule. */
export function scrubSecrets(text: string): string {
  let v = text
  for (const p of SECRET_PATTERNS) v = v.replace(p.re, p.replacement)
  return v
}

function redact(value: unknown): unknown {
  if (typeof value === 'string') {
    let v = value
    for (const p of SECRET_PATTERNS) v = v.replace(p.re, p.replacement)
    return v
  }
  if (Array.isArray(value)) return value.map(redact)
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      // Skip known-secret keys entirely.
      const lc = k.toLowerCase()
      if (lc === 'authorization' || lc === 'authtoken' || lc === 'bottoken' || lc === 'apikey' || lc === 'password' || lc === 'passwordhash' || lc === 'secret' || lc === 'token') {
        out[k] = '[REDACTED]'
      } else {
        out[k] = redact(v)
      }
    }
    return out
  }
  return value
}
